"""Train a pairwise reward ranker on AIM reward JSONL data."""

from __future__ import annotations

import argparse
import json
import random
from collections import defaultdict
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_DATA_PATH = ROOT_DIR / "reward_data" / "reward_training_data.jsonl"
DEFAULT_OUTPUT_DIR = ROOT_DIR / "reward_models" / "deberta_v3_large_ranker"
DEFAULT_MODEL_NAME = "microsoft/deberta-v3-large"


def import_training_dependencies() -> tuple[Any, Any, Any, Any, Any, Any]:
    try:
        import torch
        from torch.utils.data import Dataset
        from transformers import (
            AutoModelForSequenceClassification,
            AutoTokenizer,
            Trainer,
            TrainingArguments,
        )
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing training dependency. Install PyTorch and Transformers, for example:\n"
            "pip install torch transformers accelerate sentencepiece protobuf"
        ) from exc
    return torch, Dataset, AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune a scalar reward model with pairwise ranking loss."
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=DEFAULT_DATA_PATH,
        help="Reward JSONL data generated by scripts/generate_reward_data.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where the trained ranker and metrics are saved.",
    )
    parser.add_argument(
        "--model-name",
        default=DEFAULT_MODEL_NAME,
        help=f"Base model to fine-tune. Defaults to {DEFAULT_MODEL_NAME}.",
    )
    parser.add_argument(
        "--text-field",
        default="reward_model_input",
        help="JSONL field used as candidate input text.",
    )
    parser.add_argument(
        "--target-field",
        default="final_score",
        help="JSONL field used to derive pairwise preferences.",
    )
    parser.add_argument(
        "--group-fields",
        nargs="+",
        default=["patient_id", "mode", "turn"],
        help="Fields that define candidates from the same decision point.",
    )
    parser.add_argument(
        "--margin",
        type=float,
        default=0.4,
        help="Minimum score gap required to create a pairwise example.",
    )
    parser.add_argument(
        "--max-pairs-per-group",
        type=int,
        help="Optional cap on pairwise examples sampled from each candidate group.",
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=512,
        help="Tokenizer maximum sequence length.",
    )
    parser.add_argument(
        "--val-ratio",
        type=float,
        default=0.15,
        help="Patient-level validation split ratio.",
    )
    parser.add_argument(
        "--test-ratio",
        type=float,
        default=0.15,
        help="Patient-level test split ratio. Test data is evaluated only.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for patient-level splitting, pair sampling, and training.",
    )
    parser.add_argument(
        "--epochs",
        type=float,
        default=3.0,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-6,
        help="Fine-tuning learning rate.",
    )
    parser.add_argument(
        "--weight-decay",
        type=float,
        default=0.01,
        help="Weight decay.",
    )
    parser.add_argument(
        "--train-batch-size",
        type=int,
        default=1,
        help="Per-device training batch size.",
    )
    parser.add_argument(
        "--eval-batch-size",
        type=int,
        default=4,
        help="Per-device evaluation batch size.",
    )
    parser.add_argument(
        "--gradient-accumulation-steps",
        type=int,
        default=16,
        help="Gradient accumulation steps.",
    )
    parser.add_argument(
        "--warmup-ratio",
        type=float,
        default=0.06,
        help="Warmup ratio.",
    )
    parser.add_argument(
        "--logging-steps",
        type=int,
        default=25,
        help="Trainer logging interval.",
    )
    parser.add_argument(
        "--save-total-limit",
        type=int,
        default=2,
        help="Maximum number of checkpoints to keep.",
    )
    parser.add_argument(
        "--fp16",
        action="store_true",
        help="Use fp16 mixed precision training.",
    )
    parser.add_argument(
        "--bf16",
        action="store_true",
        help="Use bf16 mixed precision training.",
    )
    return parser.parse_args()


def load_jsonl(path: Path, text_field: str, target_field: str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                record = json.loads(stripped)
            except json.JSONDecodeError as exc:
                raise SystemExit(f"Invalid JSON on line {line_number}: {path}") from exc

            text = record.get(text_field)
            target = record.get(target_field)
            patient_id = record.get("patient_id")
            if not isinstance(text, str) or not text.strip():
                raise SystemExit(f"Missing text field {text_field!r} on line {line_number}.")
            if not isinstance(target, (int, float)):
                raise SystemExit(
                    f"Missing numeric target field {target_field!r} on line {line_number}."
                )
            if patient_id is None:
                raise SystemExit(f"Missing patient_id on line {line_number}.")
            records.append(record)

    if not records:
        raise SystemExit(f"No training records found in {path}")
    return records


def split_patient_ids(
    records: list[dict[str, Any]],
    val_ratio: float,
    test_ratio: float,
    seed: int,
) -> dict[str, set[str]]:
    if val_ratio < 0 or test_ratio < 0 or val_ratio + test_ratio >= 1:
        raise SystemExit("--val-ratio and --test-ratio must be >= 0 and sum to less than 1.")

    patient_ids = sorted({str(record["patient_id"]) for record in records})
    rng = random.Random(seed)
    rng.shuffle(patient_ids)

    total = len(patient_ids)
    test_count = round(total * test_ratio)
    val_count = round(total * val_ratio)
    if total >= 3:
        if test_ratio > 0:
            test_count = max(1, test_count)
        if val_ratio > 0:
            val_count = max(1, val_count)
    if test_count + val_count >= total:
        raise SystemExit("Not enough unique patients for the requested split ratios.")

    test_ids = set(patient_ids[:test_count])
    val_ids = set(patient_ids[test_count : test_count + val_count])
    train_ids = set(patient_ids[test_count + val_count :])
    return {"train": train_ids, "validation": val_ids, "test": test_ids}


def records_for_ids(records: list[dict[str, Any]], patient_ids: set[str]) -> list[dict[str, Any]]:
    return [record for record in records if str(record["patient_id"]) in patient_ids]


def group_key(record: dict[str, Any], fields: list[str]) -> tuple[str, ...]:
    return tuple(str(record.get(field, "")) for field in fields)


def build_pairwise_examples(
    records: list[dict[str, Any]],
    *,
    text_field: str,
    target_field: str,
    group_fields: list[str],
    margin: float,
    max_pairs_per_group: int | None,
    rng: random.Random,
) -> list[dict[str, Any]]:
    groups: dict[tuple[str, ...], list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        groups[group_key(record, group_fields)].append(record)

    pairs: list[dict[str, Any]] = []
    for key, group in groups.items():
        group_pairs: list[dict[str, Any]] = []
        for left_index, left in enumerate(group):
            for right in group[left_index + 1 :]:
                left_score = float(left[target_field])
                right_score = float(right[target_field])
                score_gap = left_score - right_score
                if abs(score_gap) < margin:
                    continue
                chosen = left if score_gap > 0 else right
                rejected = right if score_gap > 0 else left
                group_pairs.append(
                    {
                        "group_key": key,
                        "patient_id": chosen.get("patient_id"),
                        "chosen_text": chosen[text_field],
                        "rejected_text": rejected[text_field],
                        "chosen_score": float(chosen[target_field]),
                        "rejected_score": float(rejected[target_field]),
                        "chosen_candidate_id": chosen.get("candidate_id"),
                        "rejected_candidate_id": rejected.get("candidate_id"),
                    }
                )

        if max_pairs_per_group is not None and len(group_pairs) > max_pairs_per_group:
            group_pairs = rng.sample(group_pairs, max_pairs_per_group)
        pairs.extend(group_pairs)

    return pairs


class PairwiseRewardDataset:
    def __init__(
        self,
        base_dataset_class: Any,
        pairs: list[dict[str, Any]],
        tokenizer: Any,
        max_length: int,
    ) -> None:
        class _Dataset(base_dataset_class):  # type: ignore[misc, valid-type]
            def __len__(self_inner: Any) -> int:
                return len(pairs)

            def __getitem__(self_inner: Any, index: int) -> dict[str, Any]:
                pair = pairs[index]
                chosen = tokenizer(
                    pair["chosen_text"],
                    truncation=True,
                    padding="max_length",
                    max_length=max_length,
                )
                rejected = tokenizer(
                    pair["rejected_text"],
                    truncation=True,
                    padding="max_length",
                    max_length=max_length,
                )
                return {
                    "chosen_input_ids": chosen["input_ids"],
                    "chosen_attention_mask": chosen["attention_mask"],
                    "rejected_input_ids": rejected["input_ids"],
                    "rejected_attention_mask": rejected["attention_mask"],
                    "labels": 1.0,
                }

        self.dataset = _Dataset()


def make_ranker_trainer(torch: Any, Trainer: Any) -> type[Any]:
    class PairwiseRankerTrainer(Trainer):  # type: ignore[misc, valid-type]
        def compute_loss(
            self,
            model: Any,
            inputs: dict[str, Any],
            return_outputs: bool = False,
            **_: Any,
        ) -> Any:
            chosen_scores = model(
                input_ids=inputs["chosen_input_ids"],
                attention_mask=inputs["chosen_attention_mask"],
            ).logits.reshape(-1)
            rejected_scores = model(
                input_ids=inputs["rejected_input_ids"],
                attention_mask=inputs["rejected_attention_mask"],
            ).logits.reshape(-1)
            margins = chosen_scores - rejected_scores
            loss = -torch.nn.functional.logsigmoid(margins).mean()
            if return_outputs:
                return loss, {"logits": margins}
            return loss

        def prediction_step(
            self,
            model: Any,
            inputs: dict[str, Any],
            prediction_loss_only: bool,
            ignore_keys: list[str] | None = None,
        ) -> tuple[Any, Any, Any]:
            del ignore_keys
            has_labels = "labels" in inputs
            labels = inputs.get("labels") if has_labels else None
            with torch.no_grad():
                loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
            if prediction_loss_only:
                return loss.detach(), None, None
            logits = outputs["logits"].detach()
            return loss.detach(), logits, labels

    return PairwiseRankerTrainer


def make_pairwise_data_collator(torch: Any) -> Any:
    def collate(features: list[dict[str, Any]]) -> dict[str, Any]:
        return {
            key: torch.tensor([feature[key] for feature in features])
            for key in (
                "chosen_input_ids",
                "chosen_attention_mask",
                "rejected_input_ids",
                "rejected_attention_mask",
                "labels",
            )
        }

    return collate


def make_compute_metrics() -> Any:
    def compute_metrics(eval_pred: Any) -> dict[str, float]:
        predictions, _labels = eval_pred
        margins = predictions.reshape(-1).tolist()
        if not margins:
            return {"pairwise_accuracy": 0.0, "mean_margin": 0.0}
        correct = sum(1 for margin in margins if margin > 0)
        return {
            "pairwise_accuracy": correct / len(margins),
            "mean_margin": sum(margins) / len(margins),
        }

    return compute_metrics


def build_training_arguments(args: argparse.Namespace, TrainingArguments: Any) -> Any:
    common_kwargs = {
        "output_dir": str(args.output_dir),
        "learning_rate": args.learning_rate,
        "per_device_train_batch_size": args.train_batch_size,
        "per_device_eval_batch_size": args.eval_batch_size,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "num_train_epochs": args.epochs,
        "weight_decay": args.weight_decay,
        "warmup_ratio": args.warmup_ratio,
        "logging_steps": args.logging_steps,
        "save_total_limit": args.save_total_limit,
        "load_best_model_at_end": True,
        "metric_for_best_model": "pairwise_accuracy",
        "greater_is_better": True,
        "save_strategy": "epoch",
        "fp16": args.fp16,
        "bf16": args.bf16,
        "report_to": "none",
        "seed": args.seed,
        "remove_unused_columns": False,
    }
    try:
        return TrainingArguments(
            **common_kwargs,
            eval_strategy="epoch",
        )
    except TypeError:
        return TrainingArguments(
            **common_kwargs,
            evaluation_strategy="epoch",
        )


def build_trainer(
    trainer_class: type[Any],
    *,
    model: Any,
    training_args: Any,
    train_dataset: Any,
    validation_dataset: Any,
    tokenizer: Any,
    compute_metrics: Any,
    data_collator: Any,
) -> Any:
    common_kwargs = {
        "model": model,
        "args": training_args,
        "train_dataset": train_dataset,
        "eval_dataset": validation_dataset,
        "compute_metrics": compute_metrics,
        "data_collator": data_collator,
    }
    try:
        return trainer_class(
            **common_kwargs,
            processing_class=tokenizer,
        )
    except TypeError:
        return trainer_class(
            **common_kwargs,
            tokenizer=tokenizer,
        )


def save_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def pair_summary(pairs: list[dict[str, Any]]) -> dict[str, Any]:
    if not pairs:
        return {"pair_count": 0}
    gaps = [pair["chosen_score"] - pair["rejected_score"] for pair in pairs]
    return {
        "pair_count": len(pairs),
        "mean_score_gap": sum(gaps) / len(gaps),
        "min_score_gap": min(gaps),
        "max_score_gap": max(gaps),
    }


def main() -> None:
    args = parse_args()
    if args.margin < 0:
        raise SystemExit("--margin must be 0 or greater.")
    if args.max_pairs_per_group is not None and args.max_pairs_per_group < 1:
        raise SystemExit("--max-pairs-per-group must be at least 1.")

    torch, Dataset, AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments = (
        import_training_dependencies()
    )

    torch.manual_seed(args.seed)
    rng = random.Random(args.seed)
    records = load_jsonl(args.data, args.text_field, args.target_field)
    split_ids = split_patient_ids(records, args.val_ratio, args.test_ratio, args.seed)
    split_records = {
        split_name: records_for_ids(records, patient_ids)
        for split_name, patient_ids in split_ids.items()
    }
    split_pairs = {
        split_name: build_pairwise_examples(
            split_records[split_name],
            text_field=args.text_field,
            target_field=args.target_field,
            group_fields=args.group_fields,
            margin=args.margin,
            max_pairs_per_group=args.max_pairs_per_group,
            rng=rng,
        )
        for split_name in split_records
    }

    if not split_pairs["train"]:
        raise SystemExit("Training pair split is empty. Lower --margin or add more data.")
    if not split_pairs["validation"]:
        raise SystemExit("Validation pair split is empty. Lower --margin or add more data.")

    tokenizer = AutoTokenizer.from_pretrained(args.model_name, use_fast=True)
    model = AutoModelForSequenceClassification.from_pretrained(
        args.model_name,
        num_labels=1,
        problem_type="regression",
    )

    train_dataset = PairwiseRewardDataset(
        Dataset,
        split_pairs["train"],
        tokenizer,
        args.max_length,
    ).dataset
    validation_dataset = PairwiseRewardDataset(
        Dataset,
        split_pairs["validation"],
        tokenizer,
        args.max_length,
    ).dataset
    test_dataset = None
    if split_pairs["test"]:
        test_dataset = PairwiseRewardDataset(
            Dataset,
            split_pairs["test"],
            tokenizer,
            args.max_length,
        ).dataset

    training_args = build_training_arguments(args, TrainingArguments)
    trainer_class = make_ranker_trainer(torch, Trainer)
    trainer = build_trainer(
        trainer_class,
        model=model,
        training_args=training_args,
        train_dataset=train_dataset,
        validation_dataset=validation_dataset,
        tokenizer=tokenizer,
        compute_metrics=make_compute_metrics(),
        data_collator=make_pairwise_data_collator(torch),
    )

    split_summary = {
        split_name: {
            "patient_count": len(split_ids[split_name]),
            "record_count": len(split_records[split_name]),
            "patient_ids": sorted(split_ids[split_name]),
            **pair_summary(split_pairs[split_name]),
        }
        for split_name in split_ids
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    save_json(args.output_dir / "split_summary.json", split_summary)

    trainer.train()
    validation_metrics = trainer.evaluate(validation_dataset, metric_key_prefix="validation")
    test_metrics: dict[str, float] = {}
    if test_dataset is not None:
        test_metrics = trainer.evaluate(test_dataset, metric_key_prefix="test")

    trainer.save_model(args.output_dir / "final")
    tokenizer.save_pretrained(args.output_dir / "final")
    save_json(
        args.output_dir / "metrics.json",
        {
            "model_name": args.model_name,
            "data": str(args.data),
            "text_field": args.text_field,
            "target_field": args.target_field,
            "group_fields": args.group_fields,
            "margin": args.margin,
            "max_pairs_per_group": args.max_pairs_per_group,
            "max_length": args.max_length,
            "validation": validation_metrics,
            "test": test_metrics,
            "split_summary": split_summary,
        },
    )

    print(f"Saved reward ranker to {args.output_dir / 'final'}")
    print(f"Validation metrics: {validation_metrics}")
    if test_metrics:
        print(f"Test metrics: {test_metrics}")


if __name__ == "__main__":
    main()
