"""Train a DeBERTa reward model on AIM reward JSONL data."""

from __future__ import annotations

import argparse
import json
import math
import random
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_DATA_PATH = ROOT_DIR / "reward_data" / "reward_training_data.jsonl"
DEFAULT_OUTPUT_DIR = ROOT_DIR / "reward_models" / "deberta_v3_large"
DEFAULT_MODEL_NAME = "microsoft/deberta-v3-large"


def import_training_dependencies() -> tuple[Any, Any, Any, Any, Any, Any]:
    try:
        import torch
        from torch.utils.data import Dataset
        from transformers import (
            AutoModelForSequenceClassification,
            AutoTokenizer,
            Trainer,
            TrainingArguments,
        )
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing training dependency. Install PyTorch and Transformers, for example:\n"
            "pip install torch transformers accelerate sentencepiece"
        ) from exc
    return torch, Dataset, AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune a DeBERTa-v3-large scalar reward model."
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=DEFAULT_DATA_PATH,
        help="Reward JSONL data generated by scripts/generate_reward_data.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where the trained model and metrics are saved.",
    )
    parser.add_argument(
        "--model-name",
        default=DEFAULT_MODEL_NAME,
        help=f"Base model to fine-tune. Defaults to {DEFAULT_MODEL_NAME}.",
    )
    parser.add_argument(
        "--text-field",
        default="reward_model_input",
        help="JSONL field used as model input text.",
    )
    parser.add_argument(
        "--target-field",
        default="final_score",
        help="JSONL field used as scalar target.",
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=512,
        help="Tokenizer maximum sequence length.",
    )
    parser.add_argument(
        "--val-ratio",
        type=float,
        default=0.15,
        help="Patient-level validation split ratio.",
    )
    parser.add_argument(
        "--test-ratio",
        type=float,
        default=0.15,
        help="Patient-level test split ratio. Test data is evaluated only.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for patient-level splitting and training.",
    )
    parser.add_argument(
        "--epochs",
        type=float,
        default=3.0,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=1e-5,
        help="Fine-tuning learning rate.",
    )
    parser.add_argument(
        "--weight-decay",
        type=float,
        default=0.01,
        help="Weight decay.",
    )
    parser.add_argument(
        "--train-batch-size",
        type=int,
        default=2,
        help="Per-device training batch size.",
    )
    parser.add_argument(
        "--eval-batch-size",
        type=int,
        default=8,
        help="Per-device evaluation batch size.",
    )
    parser.add_argument(
        "--gradient-accumulation-steps",
        type=int,
        default=8,
        help="Gradient accumulation steps.",
    )
    parser.add_argument(
        "--warmup-ratio",
        type=float,
        default=0.06,
        help="Warmup ratio.",
    )
    parser.add_argument(
        "--logging-steps",
        type=int,
        default=25,
        help="Trainer logging interval.",
    )
    parser.add_argument(
        "--save-total-limit",
        type=int,
        default=2,
        help="Maximum number of checkpoints to keep.",
    )
    parser.add_argument(
        "--fp16",
        action="store_true",
        help="Use fp16 mixed precision training.",
    )
    parser.add_argument(
        "--bf16",
        action="store_true",
        help="Use bf16 mixed precision training.",
    )
    parser.add_argument(
        "--normalize-target",
        action="store_true",
        help="Train on scores divided by 10. Metrics are reported on the original 1-10 scale.",
    )
    return parser.parse_args()


def load_jsonl(path: Path, text_field: str, target_field: str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                record = json.loads(stripped)
            except json.JSONDecodeError as exc:
                raise SystemExit(f"Invalid JSON on line {line_number}: {path}") from exc

            text = record.get(text_field)
            target = record.get(target_field)
            patient_id = record.get("patient_id")
            if not isinstance(text, str) or not text.strip():
                raise SystemExit(f"Missing text field {text_field!r} on line {line_number}.")
            if not isinstance(target, (int, float)):
                raise SystemExit(f"Missing numeric target field {target_field!r} on line {line_number}.")
            if patient_id is None:
                raise SystemExit(f"Missing patient_id on line {line_number}.")
            records.append(record)

    if not records:
        raise SystemExit(f"No training records found in {path}")
    return records


def split_patient_ids(
    records: list[dict[str, Any]],
    val_ratio: float,
    test_ratio: float,
    seed: int,
) -> dict[str, set[str]]:
    if val_ratio < 0 or test_ratio < 0 or val_ratio + test_ratio >= 1:
        raise SystemExit("--val-ratio and --test-ratio must be >= 0 and sum to less than 1.")

    patient_ids = sorted({str(record["patient_id"]) for record in records})
    rng = random.Random(seed)
    rng.shuffle(patient_ids)

    total = len(patient_ids)
    test_count = round(total * test_ratio)
    val_count = round(total * val_ratio)
    if total >= 3:
        if test_ratio > 0:
            test_count = max(1, test_count)
        if val_ratio > 0:
            val_count = max(1, val_count)
    if test_count + val_count >= total:
        raise SystemExit("Not enough unique patients for the requested split ratios.")

    test_ids = set(patient_ids[:test_count])
    val_ids = set(patient_ids[test_count : test_count + val_count])
    train_ids = set(patient_ids[test_count + val_count :])
    return {"train": train_ids, "validation": val_ids, "test": test_ids}


def records_for_ids(records: list[dict[str, Any]], patient_ids: set[str]) -> list[dict[str, Any]]:
    return [record for record in records if str(record["patient_id"]) in patient_ids]


class RewardDataset:
    def __init__(
        self,
        base_dataset_class: Any,
        records: list[dict[str, Any]],
        tokenizer: Any,
        text_field: str,
        target_field: str,
        max_length: int,
        normalize_target: bool,
    ) -> None:
        class _Dataset(base_dataset_class):  # type: ignore[misc, valid-type]
            def __len__(self_inner: Any) -> int:
                return len(records)

            def __getitem__(self_inner: Any, index: int) -> dict[str, Any]:
                record = records[index]
                encoded = tokenizer(
                    record[text_field],
                    truncation=True,
                    max_length=max_length,
                )
                target = float(record[target_field])
                if normalize_target:
                    target /= 10.0
                encoded["labels"] = target
                return encoded

        self.dataset = _Dataset()


def pearson_correlation(xs: list[float], ys: list[float]) -> float:
    if len(xs) < 2:
        return 0.0
    mean_x = sum(xs) / len(xs)
    mean_y = sum(ys) / len(ys)
    numerator = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    denom_x = math.sqrt(sum((x - mean_x) ** 2 for x in xs))
    denom_y = math.sqrt(sum((y - mean_y) ** 2 for y in ys))
    denominator = denom_x * denom_y
    if denominator == 0:
        return 0.0
    return numerator / denominator


def make_compute_metrics(normalize_target: bool) -> Any:
    def compute_metrics(eval_pred: Any) -> dict[str, float]:
        predictions, labels = eval_pred
        preds = predictions.reshape(-1).tolist()
        refs = labels.reshape(-1).tolist()
        if normalize_target:
            preds = [prediction * 10.0 for prediction in preds]
            refs = [reference * 10.0 for reference in refs]

        errors = [prediction - reference for prediction, reference in zip(preds, refs)]
        mae = sum(abs(error) for error in errors) / len(errors)
        mse = sum(error * error for error in errors) / len(errors)
        return {
            "mae": mae,
            "rmse": math.sqrt(mse),
            "pearson": pearson_correlation(preds, refs),
        }

    return compute_metrics


def build_training_arguments(args: argparse.Namespace, TrainingArguments: Any) -> Any:
    common_kwargs = {
        "output_dir": str(args.output_dir),
        "learning_rate": args.learning_rate,
        "per_device_train_batch_size": args.train_batch_size,
        "per_device_eval_batch_size": args.eval_batch_size,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "num_train_epochs": args.epochs,
        "weight_decay": args.weight_decay,
        "warmup_ratio": args.warmup_ratio,
        "logging_steps": args.logging_steps,
        "save_total_limit": args.save_total_limit,
        "load_best_model_at_end": True,
        "metric_for_best_model": "mae",
        "greater_is_better": False,
        "save_strategy": "epoch",
        "fp16": args.fp16,
        "bf16": args.bf16,
        "report_to": "none",
        "seed": args.seed,
    }
    try:
        return TrainingArguments(
            **common_kwargs,
            eval_strategy="epoch",
        )
    except TypeError:
        return TrainingArguments(
            **common_kwargs,
            evaluation_strategy="epoch",
        )


def build_trainer(
    Trainer: Any,
    *,
    model: Any,
    training_args: Any,
    train_dataset: Any,
    validation_dataset: Any,
    tokenizer: Any,
    compute_metrics: Any,
) -> Any:
    common_kwargs = {
        "model": model,
        "args": training_args,
        "train_dataset": train_dataset,
        "eval_dataset": validation_dataset,
        "compute_metrics": compute_metrics,
    }
    try:
        return Trainer(
            **common_kwargs,
            processing_class=tokenizer,
        )
    except TypeError:
        return Trainer(
            **common_kwargs,
            tokenizer=tokenizer,
        )


def save_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def main() -> None:
    args = parse_args()
    torch, Dataset, AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments = (
        import_training_dependencies()
    )

    torch.manual_seed(args.seed)
    records = load_jsonl(args.data, args.text_field, args.target_field)
    split_ids = split_patient_ids(records, args.val_ratio, args.test_ratio, args.seed)
    split_records = {
        split_name: records_for_ids(records, patient_ids)
        for split_name, patient_ids in split_ids.items()
    }

    if not split_records["train"]:
        raise SystemExit("Training split is empty.")
    if not split_records["validation"]:
        raise SystemExit("Validation split is empty. Increase data or set a validation ratio.")

    tokenizer = AutoTokenizer.from_pretrained(args.model_name, use_fast=True)
    model = AutoModelForSequenceClassification.from_pretrained(
        args.model_name,
        num_labels=1,
        problem_type="regression",
    )

    train_dataset = RewardDataset(
        Dataset,
        split_records["train"],
        tokenizer,
        args.text_field,
        args.target_field,
        args.max_length,
        args.normalize_target,
    ).dataset
    validation_dataset = RewardDataset(
        Dataset,
        split_records["validation"],
        tokenizer,
        args.text_field,
        args.target_field,
        args.max_length,
        args.normalize_target,
    ).dataset
    test_dataset = None
    if split_records["test"]:
        test_dataset = RewardDataset(
            Dataset,
            split_records["test"],
            tokenizer,
            args.text_field,
            args.target_field,
            args.max_length,
            args.normalize_target,
        ).dataset

    training_args = build_training_arguments(args, TrainingArguments)
    trainer = build_trainer(
        Trainer,
        model=model,
        training_args=training_args,
        train_dataset=train_dataset,
        validation_dataset=validation_dataset,
        tokenizer=tokenizer,
        compute_metrics=make_compute_metrics(args.normalize_target),
    )

    split_summary = {
        split_name: {
            "patient_count": len(patient_ids),
            "record_count": len(split_records[split_name]),
            "patient_ids": sorted(patient_ids),
        }
        for split_name, patient_ids in split_ids.items()
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    save_json(args.output_dir / "split_summary.json", split_summary)

    trainer.train()
    validation_metrics = trainer.evaluate(validation_dataset, metric_key_prefix="validation")
    test_metrics: dict[str, float] = {}
    if test_dataset is not None:
        test_metrics = trainer.evaluate(test_dataset, metric_key_prefix="test")

    trainer.save_model(args.output_dir / "final")
    tokenizer.save_pretrained(args.output_dir / "final")
    save_json(
        args.output_dir / "metrics.json",
        {
            "model_name": args.model_name,
            "data": str(args.data),
            "text_field": args.text_field,
            "target_field": args.target_field,
            "max_length": args.max_length,
            "normalize_target": args.normalize_target,
            "validation": validation_metrics,
            "test": test_metrics,
            "split_summary": split_summary,
        },
    )

    print(f"Saved reward model to {args.output_dir / 'final'}")
    print(f"Validation metrics: {validation_metrics}")
    if test_metrics:
        print(f"Test metrics: {test_metrics}")


if __name__ == "__main__":
    main()
